name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  windows-build-test:
    name: windows build & test
    strategy:
      matrix:
        runner: [windows-2019, windows-2022]
    runs-on: ${{ matrix.runner }}
    steps:
      - run: |
          mkdir C:\kuzu
          git clone https://github.com/kuzudb/kuzu.git C:\kuzu
          cd C:\kuzu
          git switch ci-more-platforms

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Ensure Python dependencies
        shell: cmd
        working-directory: C:\kuzu
        run: |
          pip install torch~=2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --user -r tools\python_api\requirements_dev.txt -f https://data.pyg.org/whl/torch-2.0.0+cpu.html

      - name: Ensure Node.js dependencies
        shell: cmd
        working-directory: C:\kuzu\tools\nodejs_api
        run: npm install --include=dev

      - name: Build
        shell: cmd
        working-directory: C:\kuzu
        run: make release NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Test
        shell: cmd
        working-directory: C:\kuzu
        run: make test NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: C example
        shell: cmd
        working-directory: C:\kuzu\examples\c
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
        continue-on-error: true

      - name: C++ example
        shell: cmd
        working-directory: C:\kuzu\examples\cpp
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
        continue-on-error: true

      - name: Python test
        shell: cmd
        working-directory: C:\kuzu
        run: make pytest NUM_THREADS=%NUMBER_OF_PROCESSORS%
        continue-on-error: true

      - name: Node.js test
        shell: cmd
        working-directory: C:\kuzu
        run: make nodejstest NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Java test
        shell: cmd
        working-directory: C:\kuzu
        run: make javatest NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Rust share build
        shell: cmd
        working-directory: C:\kuzu
        run: (echo [workspace]& echo members = ["tools/rust_api","examples/rust"]) > Cargo.toml

      - name: Rust test
        shell: cmd
        working-directory: C:\kuzu\tools\rust_api
        run: |
          set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
          set KUZU_TESTING=1
          set CFLAGS=/MDd
          set CXXFLAGS=/MDd /std:c++20
          set CARGO_BUILD_JOBS=%NUMBER_OF_PROCESSORS%
          cargo update -p half@2.3.1 --precise '2.2.1'
          cargo update -p time --precise '0.3.23'
          cargo test --features arrow -- --test-threads=1
        continue-on-error: true

      - name: Rust example
        shell: cmd
        working-directory: C:\kuzu\examples\rust
        run: |
          set CARGO_BUILD_JOBS=%NUMBER_OF_PROCESSORS%
          cargo build --features arrow
        continue-on-error: true
